### ISSUE TITLE
Bezier-curve

### ISSUE THREAD

**Issue by HopeCollector** [HopeCollector/windowsAPI#2]
当1/i接近1时，坐标几乎不会变化，这时c语言本身的除法规则决定的，有什么办法能绕开[代码](https://github.com/HopeCollector/windowsAPI/blob/c5/Chapter5/Chapter5.4%28Bezier%29/main.c)

**Comment by crackhopper** [comment]
link 一下你的commit。

**Comment by crackhopper** [comment]
b67ed27 直接输入commit的SHA值就能link到。给你举个例子。

**Comment by crackhopper** [comment]
另外，就是还可以link到具体的行 ，这个是对特定的commit的上面的代码的link：
https://github.com/HopeCollector/windowsAPI/blob/b67ed27beb25c7fc77642db66940df70000c26fc/Chapter5/Chapter5.4(Bezier)/main.c#L56

**Comment by HopeCollector** [comment]
怎么做到的

**Comment by crackhopper** [comment]
对某个分支上的文件的具体行link https://github.com/HopeCollector/windowsAPI/blob/c5/Chapter5/Chapter5.4(Bezier)/main.c#L56

另外，在github上面，也可以进行代码批注，也可以link到批注上。

**Comment by HopeCollector** [comment]
问题啊，我的问题啊，是我想错了么

**Comment by crackhopper** [comment]
https://github.com/HopeCollector/windowsAPI/commit/b67ed27beb25c7fc77642db66940df70000c26fc#diff-02edc3681d10cd8b3363f9b67404cb42R1

直接拷贝超链接就行了，你点击一下这个看看。

要充分利用github。

**Comment by HopeCollector** [comment]
以前的二进制我都没注意过

**Comment by crackhopper** [comment]
再给你看看，各种各样的link，在别处可以link到issue里面。https://github.com/HopeCollector/windowsAPI/commit/b67ed27beb25c7fc77642db66940df70000c26fc#comments

**Comment by crackhopper** [comment]
恩，搞明白link怎么用之后，你在自己代码里面具体位置标出问题。

如果可以的话，不要一下子提交太多行。要不然看起来也费劲。我感觉每次300行以内是比较好的。
