### ISSUE TITLE
贝塞尔曲线问题

### ISSUE THREAD

**Issue by HopeCollector** [HopeCollector/windowsAPI#4]
@crackhopper 当1/i接近1时得出来的结果变化也来越小，导致画出来的线越来越像直线，但是按照c语言的除法规则，得到的结果就是直线！[出现问题的代码](https://github.com/HopeCollector/windowsAPI/blob/c5/Chapter5/Chapter5.4%28Bezier%29/main.c#L146)

**Comment by HopeCollector** [comment]
@crackhopper

**Comment by crackhopper** [comment]
搞定了之后，说一下怎么回事。 @HopeCollector
